### ISSUE TITLE
Connecting to PPK through J-Link makes other J-Link lose target connection

### ISSUE THREAD

**Issue by jonas-schievink** [NordicSemiconductor/pc-nrfconnect-ppk#100]
I have 2 standalone J-Links connected to my system, one of which is used for the PPK and the other is used to debug my application. If I use the PPK software to connect to the PPK, and then start the JLinkGDBServer to connect to the other J-Link, everything works fine. However, if I do it the other way around, or reconnect to the PPK while the JLinkGDBServer is running, the GDB server will lose the connection to the target and close.

This might well be a bug in the J-Link libraries, in which case feel free to just close this.

**Comment by jonas-schievink** [comment]
Ah, this is probably just caused by the target voltage supply from the PPK being interrupted. Still, would be nice if I didn't have to restart the GDB server every time.

**Comment by wlgrd** [comment]
So just to be sure, you are powering the other J-Link device with the PPK?

**Comment by jonas-schievink** [comment]
The target, yes, both J-Links are USB-powered

**Comment by wlgrd** [comment]
If vtarget to jlink is lost, then there are no way of keeping the gdb server as far as I know. The bootup of the ppk needs to turn off the DUT in order to do some offset calculations. Changing this may lead to erroneous measurements.

**Comment by jonas-schievink** [comment]
Yeah I thought so, that's unfortunate, but I'll manage.
