### ISSUE TITLE
Sampling parameters - RAM

### ISSUE THREAD

**Issue by mislavkulas** [NordicSemiconductor/pc-nrfconnect-ppk#206]
Can you please add that we can allocate more of the RAM memory that we can then log more than 432 seconds on 100 000 samples per seconds? I see that in the app si always max amount of allocated RAM memory 172.8 MB.

**Comment by nicolai-nordic** [comment]
Hello @mislavkulas, thanks for the feedback. This is definitely something we can consider. I will put it on the backlog and bring it up during the next planning.

**Comment by mislavkulas** [comment]
@nicolai-nordic  thank you 👍

**Comment by mislavkulas** [comment]
Have you maybe some updates?

**Comment by nicolai-nordic** [comment]
Hello @mislavkulas. Unfortunately we have spent most of our time upgrading the infrastructure of nRF Connect for Desktop the last months, so we have not had time to look into this issue yet. However, the 3.9.1 release that came out on Friday seems to have fixed the most common issues, so now it looks like we will have some time to look into this. I will keep you posted with any updates.

**Comment by aadnekar** [comment]
Hello @mislavkulas, we have now been able to work on the feature you requested. The new changes have been accepted in pull request https://github.com/NordicSemiconductor/pc-nrfconnect-ppk/pull/220, and we aim to include it in the next release.
Thanks a lot for the feedback, and I hope you will enjoy the new feature 😃

**Comment by mislavkulas** [comment]
@aadnekar thank you :D

**Comment by nicolai-nordic** [comment]
@mislavkulas, this feature is now available in PPK v3.3.0. For now it's only available under Advanced Options which is visible if you hit `CTRL` + `ALT` + `SHIFT` + `A`. We do persist the value selected though, so it should be sufficient to just perform the action once (or whenever you want to update it). It is likely that we will make this more available in the near future.
