### ISSUE TITLE
[feature] PPK mobile app

### ISSUE THREAD

**Issue by cederom** [NordicSemiconductor/pc-nrfconnect-ppk#294]
Hello world :-)

Would it be possible to provide Mobile Application for PPK / nRF Connect? I am mostly interested in Android. That would be really handy :-)

I am working on FreeBSD and nRF Connect is not available here :-( Mobile would be great alternative to a separate computer :-)

I can see there is a nRF Connect mobile application but there is no PPK module over there (maybe this is different application?). JS+Electron should make it fairly easy to implement :-)

Thanks for considering :-)
Tomek

**Comment by datenreisender** [comment]
AFAIK the existing nRF Connect for Mobile apps are all working with wireless connections to devices while the PPK needs a wired connection. 

I also know of no plans to work on a mobile PPK application, so I will close this as won't fix (in the foreseeable future).
