### ISSUE TITLE
Logarithmic scale

### ISSUE THREAD

**Issue by danielkucera** [NordicSemiconductor/pc-nrfconnect-ppk#296]
Hello,
the device is great!
However, would it be possible to make the Y-axis (with current) logarithmic? 
My device has a wide range of consumption so it would be easier to read uA values when there is also 100mA  on the same scale.
![Screenshot from 2022-11-27 13-20-21](https://user-images.githubusercontent.com/1734256/204135137-3971e698-2367-4bf9-81ba-57d45acb3a77.png)

**Comment by danielkucera** [comment]
I was able to change the axis but I am not that pro in js to be able to make the button work. Can you please help?

![image](https://user-images.githubusercontent.com/1734256/204158496-ecf29b56-9bb4-4f84-bbef-993cdd908c5c.png)

my code is in #297

**Comment by danielkucera** [comment]
I was able to change the axis but I am not that pro in js to be able to make the button work. Can you please help?
Some hint is here: https://stackoverflow.com/questions/42625579/dynamically-update-the-scale-type-of-chartjs-graph

![image](https://user-images.githubusercontent.com/1734256/204158496-ecf29b56-9bb4-4f84-bbef-993cdd908c5c.png)

my code is in #297

**Comment by aadnekar** [comment]
PR is merged: https://github.com/NordicSemiconductor/pc-nrfconnect-ppk/pull/297
