### ISSUE TITLE
Power Profiler max current shows wrong units

### ISSUE THREAD

**Issue by markb-EE** [NordicSemiconductor/pc-nrfconnect-ppk#375]
The power profiler max measurement is showing using of A (amps) when I think it should be showing units of mA (milliamps):

![image](https://github.com/NordicSemiconductor/pc-nrfconnect-ppk/assets/8332189/3523ad5a-a2f4-4eba-8ad1-5e0b6cdb7d08)

**Comment by markb-EE** [comment]
Version 4.0.0-beta1

**Comment by datenreisender** [comment]
There was a bug in your version, which was [fixed](https://github.com/NordicSemiconductor/pc-nrfconnect-ppk/commit/aea3d61b57ceede3e89b3cc2e134800f828cc2d8) in [v4.0.0-beta2](https://github.com/NordicSemiconductor/pc-nrfconnect-ppk/releases/tag/v4.0.0-beta2). Please upgrade to the latest version.
