### ISSUE TITLE
[Feature Requests] Battery Life Simulation and Selection

### ISSUE THREAD

**Issue by microbuilder** [NordicSemiconductor/pc-nrfconnect-ppk#84]
# Battery Life Estimation

Based on the average current measurement, it would be helpful to customers to have the option to plug in some basic battery details and have the PPK estimate battery life based on those parameters and the capture current draw.

I have a [Power Monitor from Monsoon](https://mostly-tech.com/tag/power-profile/) that does this amongst other things and find it a useful feature, but that device may be prohibitively expensive for some people compared to the PPK.

# Range Subset Selection

A second useful feature would be able to make a selection in the captured waveforms and only display the avg/min/max values for that selection, since you may only want to analyze a specific subset of the data. It would be great to be able to just zoom in or out and mouse-select a range with a rectangle selector.

# Dynamic Mouser-Over Selection

Finally, when you move your mouse around in the captured waveform, something that displays the values at **that specific point** would be useful rather than guessing visually what the exact value is?

The tool already fills a need, but I wanted to make some suggestions to try to make it even more useful. Thanks for the work on this so far, though!

**Comment by bihanssen** [comment]
Hi @microbuilder,
Your feature requests are valid and would increase the usability of the app, agreed. Have added to our backlog for further evaluation.
Thanks for the input, closing this ticket.
