### ISSUE TITLE
Cannot read property 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by imcort** [NordicSemiconductor/pc-nrfconnect-ppk#94]
[devzone link](https://devzone.nordicsemi.com/f/nordic-q-a/49391/nrf-connect-error-while-setting-up-device-cannot-read-property-tolowercase-of-undefined/196791)
I have the same issue when using the nRF Connect v2.7.0 or v3.0.0, but the v2.6.0 works correctly.

**Comment by victor888866** [comment]
I have the same issue too

**Comment by minchingho** [comment]
I also have the same issue on Mac.
